ideas/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',home,name="home"),
    path('profile/',include('iprofile.urls')),
    path('ideas/',include(('Content.urls','ideas')),name='ideas'),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Content/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone
# Create your models here.






class ICategory(models.Model):

    name = models.CharField('Имя категорий', max_length=255)
    ficon = models.CharField('Для иконки',max_length=255)
    photo = models.ImageField('Фото категорий',blank=True,null=True,upload_to="IcatP/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категорий"

class Ideas(models.Model):
    title = models.CharField("Название идей", max_length=255)
    description = models.TextField("Описание идей")
    created_at = models.DateTimeField('Создано',default=timezone.now)
    author = models.ForeignKey(User,verbose_name="Автор", related_name="ideas",on_delete=models.CASCADE)
    category = models.ForeignKey(ICategory,on_delete=models.CASCADE,blank=True,null=True,default=None,related_name="idea")

    def __str__(self):
        return self.title

    def getall(self):


        idea_id = self.id
        rating = Rating.objects.filter(idea_id=idea_id)
        # try:
        #     rating = Rating.objects.get(user_id=id,idea_id=idea_id)
        # except DoesNotExist:
        #     rating = "Вы уже лайкали"

        return rating
        
   

    def mainRating(self):
        count = 1
        counti = 0
        for rating in self.rating.all():
            count += rating.overall_ratinge()
            counti += 1

        result = int(count/counti)
        return result


    def time(self):
        lastime =timezone.now() - self.created_at
        data = int(lastime.total_seconds())
        totaldata = data / 60
        return int(totaldata)

    class Meta:
        verbose_name = "Идея"
        verbose_name_plural = "Идей"

class Rating(models.Model):
    rating1 = models.IntegerField("Rating1",default=0)
    rating2 = models.IntegerField("Rating2",default=0)
    rating3 = models.IntegerField("Rating3",default=0)
    rating4 = models.IntegerField("Rating4",default=0)
    rating5 = models.IntegerField("Rating5",default=0)
    user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,default=None,related_name="rating")
    idea = models.ForeignKey(Ideas,on_delete=models.CASCADE,blank=True,null=True,default=None,related_name="rating")
    
    
    def getRateBoll(request,self):
        if self.user == request.user:
            return "yes"
        else:
            return "no"
        
          

    def overall_ratinge(self):
        overall_ratings = (self.rating1 + self.rating2 + self.rating3 + self.rating4 + self.rating5) / 5
        return int(overall_ratings)


    def __str__(self):
        overall_rating = self.overall_ratinge()
        return str(overall_rating)

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Photo(models.Model):
    photo = models.ImageField("photo", upload_to="Images/")
    ideas = models.ForeignKey(Ideas, related_name="photo", on_delete=models.CASCADE)

    def __str__(self):
        return self.ideas.title

    

    class Meta:
        verbose_name = "Фото для Идей"
        verbose_name_plural = "Фото для Идей"

iprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Specialization(models.Model):

    name = models.CharField('Имя специлизаций', max_length=255)

    def __str__(self):

        return self.name


class Profile(models.Model):

    user = models.OneToOneField(User,blank=True,null=True,on_delete=models.CASCADE,related_name="profile")
    photo = models.ImageField('Фото профиля',upload_to="ProfileImg/",blank=True,null=True)
    specialization = models.ForeignKey(Specialization,blank=True,null=True,on_delete=models.CASCADE,default=None)

templates/accounts/login.html
{% extends 'app.html' %}
{% load static %}
{% block content %}

<div class="registration mt-5">
    <div class="container">
        <div class="grid2 ">
            <div class="grid-item">
                <h1 class="reg-title">
                    Авторизация на Usyn
                </h1>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }} message-item"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="grid1 mt-5">
            <form method="POST" class="form" action="{% url 'login' %}">
                {% csrf_token %}
              
                <div class="form-group">
                    <!-- <label class="label" for="id_username">{{form.email.label}}</label> -->
                    {{form.username}}
                </div>
                <div class="form-group">
                    <!-- <label class="label" for="id_username">{{form.password1.label}}</label> -->
                    {{form.password1}}
                </div>
                <div class="btns-group">
                    <button type="submit" class="btn">Войти</button>
                    <a class="btn btn-inline" href="{% url 'login' %}">Регистрация</a>
                </div>
               
            </form>
           
            <!-- end of form -->
        </div>
    </div>
    
</div>

    

{% endblock %}

templates/accounts/profilereg.html
{% extends 'app.html' %}
{% load static %}
{% block content %}
<div class="registration mt-5">
    <div class="container">
        <div class="profile-edit">
            {% if messages %}
            <ul class="messages ">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} message-item"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="grid1 mt-3">
                <form action="{% url 'profilereg' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="grid2-min">
                        <div class="grid-item">
                            <input type="hidden" name="user" id="id_user" value="{{request.user.id}}">     
                            <div class="fileform">
                                <div id="fileformlabel"></div>
                              
                                <input id="upload" type="file" name="photo" accept="image/*" onchange="getName(this.value);" />   
                            </div>
                        </div>
                        <div class="grid-item">
                            <div class="reg-name">{{request.user.username}}</div>
                            <label for="id_specialization" class="form-control">Выберите специлизацию</label>
                            {{profile.specialization}}
                            <div class="btn-single mt-3">
                                <button class="btn">Подтвердить</button>
                            </div>
                            
                        </div>
                    </div>
                    
                </form>
            {{form.errors}}
        </div>
        </div>
    </div>
   
{% endblock %}

templates/accounts/register.html
{% extends 'app.html' %}
{% load static %}
{% block content %}

    <div class="registration mt-5">
        <div class="container">
            <div class="grid2 ">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }} message-item"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <div class="grid-item mt-5">
                    <div class="reg-img_b">
                        <img src="{% static 'img/path504-3.png' %}" class="reg-img">
                    </div>
                   
                </div>
                <div class="grid-item">
                    <h1 class="reg-title">
                        Регистрация на Usyn
                    </h1>
                    <p class="reg-p">
                        1) Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>
                        2) Vestibulum ornare mauris venenatis, tempus arcu et, convallis velit. <br>
                        3) Vivamus sagittis mi non velit pellentesque ultrices. <br>
                        4) Quisque accumsan augue quis neque tincidunt, quis mattis magna interdum. <br>
                        5)Nulla at ipsum at lacus rhoncus ultrices scelerisque ac orci in plact tellus sit amet semper mollis. <br>
                        6) Fusce quis nulla sed metus semper laoreet. <br>
                        7) Nam cursus libero non ullamcorper vulputate.
                    </p>
                </div>
            </div>
            <div class="grid1 mt-5">
                <form method="POST" class="form" action="{% url 'register' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <!-- <label for="id_username">{{form.username.label}}</label> -->
                        {{form.username}}
                    </div>
                    <div class="form-group">
                        <!-- <label class="label" for="id_username">{{form.email.label}}</label> -->
                        {{form.email}}
                    </div>
                    <div class="form-group">
                        <!-- <label class="label" for="id_username">{{form.password1.label}}</label> -->
                        {{form.password1}}
                    </div>
                    <div class="form-group">
                        <!-- <label class="label" for="id_username">{{form.password2.label}}</label> -->
                        {{form.password2}}
                    </div>
                    <div class="btns-group">
                        <button type="submit" class="btn">Далее</button>
                        <a class="btn btn-inline" href="{% url 'login' %}">Войти</a>
                    </div>
                   
                </form>
                {{form.errors}}
                <!-- end of form -->
            </div>
        </div>
        
    </div>

                            
                      
                       
    
    <script src="js/plugins.min.js"></script>
    <script src="js/app.js"></script>
{% endblock %}